
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  # SSL configuratie 
  ssl_certificate: /config/fullchain.pem
  ssl_key: /config/privkey.pem

  # IP ban voor brute-force bescherming 
  ip_ban_enabled: true
  login_attempts_threshold: 5

  # Server host (optioneel, maar aangeraden) 
  server_host: 0.0.0.0
  server_port: 8123
