services:
  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /srv/docker/mqtt/config:/mosquitto/config
      - /srv/docker/mqtt/log:/mosquitto/log
      - /srv/docker/mqtt/data:/mosquitto/data
    environment:
      - TZ=Europe/Brussels
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
