services:
  zigbee2mqtt:
    container_name: zigbee2mqtt
    privileged: true
    image: koenkk/zigbee2mqtt
    volumes:
      - /srv/docker/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - "8080:8080"
    environment:
      - TZ=Europe/Brussels
    group_add:
      - dialout
    user: 1000:1000
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
